create table contaminacion (
fabrica_fabrica_latLon varchar(30),
fabrica_cantEmple numeric,
fabrica_empresa_nombre varchar(30),
fabrica_empresa_factAnual numeric,
fabrica_rubro_tipoID numeric,
fabrica_rubro_tipoDesc varchar(30),
fabrica_ciudad_nombre varchar(30),
fabrica_ciudad_poblacion numeric,
fabrica_pais_nombre varchar(30),
fabrica_pais_the_geom geometry,
inicio_temporal_dia Timestamp,
inicio_month_mes varchar(30),
inicio_month_nombre varchar(30), 
inicio_year_anio varchar(30),
inicio_year_esBisiesto numeric,
fin_temporal_dia Timestamp,
fin_month_mes varchar(30),
fin_month_nombre varchar(30),
fin_year_anio varchar(30),
fin_year_esBisiesto numeric,
sustanciaDim_sustancia_denominacion varchar(30),
emision numeric,
emisionMala numeric,
nube integer,
primary key(fabrica_fabrica_latLon , inicio_temporal_dia, fin_temporal_dia, sustanciaDim_sustancia_denominacion)
);